CREATE TABLE IF NOT EXISTS project_techs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  projectId INT UNSIGNED NOT NULL,
  techId INT UNSIGNED NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE
);