CREATE TABLE IF NOT EXISTS projects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId INT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  tags JSON NULL,
  description TEXT,
  link VARCHAR(255),
  githubLink VARCHAR(255),

  status ENUM('pending', 'active', 'completed', 'archived') NOT NULL DEFAULT 'pending',
  isDraft BOOLEAN NOT NULL DEFAULT TRUE,
  displayOrder INT UNSIGNED NOT NULL DEFAULT 0,

  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);