CREATE TABLE IF NOT EXISTS profiles (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId INT UNSIGNED NOT NULL,
  bio TEXT,
  phone VARCHAR(20),
  website VARCHAR(255),
  location VARCHAR(255),
  profileImage VARCHAR(255),

  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY (userId),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
