ALTER TABLE users ADD COLUMN emailVerifiedAt DATETIME NULL;

UPDATE users SET emailVerifiedAt = NOW() WHERE emailVerifiedAt IS NULL;

CREATE TABLE email_verification_otps (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	userId INT UNSIGNED NOT NULL,
	email VARCHAR(255) NOT NULL,
	otpHash CHAR(64) NOT NULL,
	expiresAt DATETIME NOT NULL,
	usedAt DATETIME NULL,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id),
	FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
)
