CREATE TABLE IF NOT EXISTS experience_techs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  experienceId INT UNSIGNED NOT NULL,
  techId INT UNSIGNED NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  FOREIGN KEY (experienceId) REFERENCES experiences(id) ON DELETE CASCADE
);
