CREATE TABLE password_reset_tokens (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	userId INT UNSIGNED NOT NULL,
	tokenHash CHAR(64) NOT NULL,
	expiresAt DATETIME NOT NULL,
	usedAt DATETIME NULL,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id),
	FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
)
