package seeders

import (
	"database/sql"
	"fmt"
	"strings"
)

type Technology struct {
	Name     string
	Category string
}

func normalizeSlug(name string) string {
	s := strings.ToLower(strings.TrimSpace(name))

	s = strings.ReplaceAll(s, ".js", "")
	s = strings.ReplaceAll(s, ".css", "")
	s = strings.ReplaceAll(s, " ", "-")

	return s
}

func SeedTechnologies(db *sql.DB) error {

	techs := []Technology{
		// languages
		{Name: "JavaScript", Category: "language"},
		{Name: "TypeScript", Category: "language"},
		{Name: "Python", Category: "language"},
		{Name: "Go", Category: "language"},
		{Name: "Rust", Category: "language"},
		{Name: "Java", Category: "language"},
		{Name: "Kotlin", Category: "language"},
		{Name: "C#", Category: "language"},
		{Name: "C++", Category: "language"},
		{Name: "C", Category: "language"},
		{Name: "Swift", Category: "language"},
		{Name: "Ruby", Category: "language"},
		{Name: "PHP", Category: "language"},
		{Name: "Scala", Category: "language"},
		{Name: "Dart", Category: "language"},
		{Name: "Elixir", Category: "language"},
		{Name: "Clojure", Category: "language"},
		{Name: "Haskell", Category: "language"},
		{Name: "Lua", Category: "language"},
		{Name: "Perl", Category: "language"},
		{Name: "R", Category: "language"},
		{Name: "Julia", Category: "language"},
		{Name: "Zig", Category: "language"},
		{Name: "Nim", Category: "language"},
		{Name: "Crystal", Category: "language"},
		{Name: "Erlang", Category: "language"},
		{Name: "Groovy", Category: "language"},
		{Name: "F#", Category: "language"},
		{Name: "OCaml", Category: "language"},
		{Name: "D", Category: "language"},
		{Name: "Solidity", Category: "language"},
		{Name: "Shell", Category: "language"},
		{Name: "PowerShell", Category: "language"},
		{Name: "GraphQL", Category: "language"},
		{Name: "V", Category: "language"},
		{Name: "Gleam", Category: "language"},
		{Name: "ReasonML", Category: "language"},
		{Name: "Pony", Category: "language"},
		{Name: "Fortran", Category: "language"},
		{Name: "COBOL", Category: "language"},
		{Name: "Ada", Category: "language"},
		{Name: "Pascal", Category: "language"},
		{Name: "Smalltalk", Category: "language"},
		{Name: "Prolog", Category: "language"},
		{Name: "Lisp", Category: "language"},
		{Name: "Scheme", Category: "language"},
		{Name: "Racket", Category: "language"},
		{Name: "Tcl", Category: "language"},
		{Name: "Awk", Category: "language"},
		{Name: "Sed", Category: "language"},
		{Name: "VHDL", Category: "language"},
		{Name: "Verilog", Category: "language"},
		{Name: "Assembly", Category: "language"},
		{Name: "WebAssembly", Category: "language"},

		// frontend frameworks & libraries
		{Name: "React", Category: "frontend"},
		{Name: "Vue.js", Category: "frontend"},
		{Name: "Angular", Category: "frontend"},
		{Name: "Svelte", Category: "frontend"},
		{Name: "SolidJS", Category: "frontend"},
		{Name: "Qwik", Category: "frontend"},
		{Name: "Preact", Category: "frontend"},
		{Name: "Alpine.js", Category: "frontend"},
		{Name: "Lit", Category: "frontend"},
		{Name: "HTMX", Category: "frontend"},
		{Name: "Stimulus", Category: "frontend"},
		{Name: "Ember.js", Category: "frontend"},
		{Name: "Backbone.js", Category: "frontend"},
		{Name: "Mithril", Category: "frontend"},
		{Name: "Marko", Category: "frontend"},
		{Name: "Riot.js", Category: "frontend"},
		{Name: "jQuery", Category: "frontend"},

		// CSS frameworks & preprocessors
		{Name: "Bootstrap", Category: "frontend"},
		{Name: "Tailwind CSS", Category: "frontend"},
		{Name: "Sass/SCSS", Category: "frontend"},
		{Name: "Less", Category: "frontend"},
		{Name: "PostCSS", Category: "frontend"},
		{Name: "UnoCSS", Category: "frontend"},
		{Name: "Windi CSS", Category: "frontend"},
		{Name: "Open Props", Category: "frontend"},
		{Name: "Styled Components", Category: "frontend"},
		{Name: "CSS Modules", Category: "frontend"},
		{Name: "Vanilla Extract", Category: "frontend"},
		{Name: "Stitches", Category: "frontend"},
		{Name: "Panda CSS", Category: "frontend"},
		{Name: "Linaria", Category: "frontend"},
		{Name: "Bulma", Category: "frontend"},
		{Name: "Foundation", Category: "frontend"},
		{Name: "Semantic UI", Category: "frontend"},
		{Name: "Tachyons", Category: "frontend"},
		{Name: "DaisyUI", Category: "frontend"},
		{Name: "Chakra UI", Category: "frontend"},
		{Name: "MUI", Category: "frontend"},
		{Name: "Ant Design", Category: "frontend"},
		{Name: "Shadcn/ui", Category: "frontend"},
		{Name: "Radix UI", Category: "frontend"},
		{Name: "Headless UI", Category: "frontend"},
		{Name: "PrimeReact", Category: "frontend"},
		{Name: "PrimeNG", Category: "frontend"},
		{Name: "PrimeVue", Category: "frontend"},

		// state management
		{Name: "Redux", Category: "frontend"},
		{Name: "Zustand", Category: "frontend"},
		{Name: "Jotai", Category: "frontend"},
		{Name: "Recoil", Category: "frontend"},
		{Name: "Valtio", Category: "frontend"},
		{Name: "Pinia", Category: "frontend"},
		{Name: "Vuex", Category: "frontend"},
		{Name: "MobX", Category: "frontend"},
		{Name: "NgRx", Category: "frontend"},
		{Name: "Signals", Category: "frontend"},
		{Name: "Nano Stores", Category: "frontend"},

		// animation & graphics
		{Name: "Framer Motion", Category: "frontend"},
		{Name: "GSAP", Category: "frontend"},
		{Name: "Anime.js", Category: "frontend"},
		{Name: "Three.js", Category: "frontend"},
		{Name: "D3.js", Category: "frontend"},
		{Name: "Lottie", Category: "frontend"},
		{Name: "Motion", Category: "frontend"},
		{Name: "React Spring", Category: "frontend"},
		{Name: "React Transition Group", Category: "frontend"},
		{Name: "p5.js", Category: "frontend"},
		{Name: "Chart.js", Category: "frontend"},
		{Name: "Recharts", Category: "frontend"},

		// meta-frameworks & full-stack
		{Name: "Next.js", Category: "frontend"},
		{Name: "Nuxt.js", Category: "frontend"},
		{Name: "Astro", Category: "frontend"},
		{Name: "Remix", Category: "frontend"},
		{Name: "Gatsby", Category: "frontend"},
		{Name: "Eleventy", Category: "frontend"},
		{Name: "Docusaurus", Category: "frontend"},
		{Name: "Fresh", Category: "frontend"},
		{Name: "Rspress", Category: "frontend"},
		{Name: "Rakkas", Category: "frontend"},

		// backend frameworks & runtimes
		{Name: "Node.js", Category: "backend"},
		{Name: "Deno", Category: "backend"},
		{Name: "Bun", Category: "backend"},
		{Name: "Express", Category: "backend"},
		{Name: "NestJS", Category: "backend"},
		{Name: "Fastify", Category: "backend"},
		{Name: "Koa", Category: "backend"},
		{Name: "Hapi", Category: "backend"},
		{Name: "Socket.io", Category: "backend"},
		{Name: "Laravel", Category: "backend"},
		{Name: "Symfony", Category: "backend"},
		{Name: "CakePHP", Category: "backend"},
		{Name: "CodeIgniter", Category: "backend"},
		{Name: "Django", Category: "backend"},
		{Name: "Flask", Category: "backend"},
		{Name: "FastAPI", Category: "backend"},
		{Name: "Tornado", Category: "backend"},
		{Name: "Spring Boot", Category: "backend"},
		{Name: "Spring", Category: "backend"},
		{Name: "Micronaut", Category: "backend"},
		{Name: "Quarkus", Category: "backend"},
		{Name: "Gin", Category: "backend"},
		{Name: "Fiber", Category: "backend"},
		{Name: "Echo", Category: "backend"},
		{Name: "Chi", Category: "backend"},
		{Name: "Revel", Category: "backend"},
		{Name: "Buffalo", Category: "backend"},
		{Name: "Actix", Category: "backend"},
		{Name: "Rocket", Category: "backend"},
		{Name: "Axum", Category: "backend"},
		{Name: "Ruby on Rails", Category: "backend"},
		{Name: "Sinatra", Category: "backend"},
		{Name: "Phoenix", Category: "backend"},
		{Name: "Plug", Category: "backend"},
		{Name: "ASP.NET", Category: "backend"},
		{Name: "ASP.NET Core", Category: "backend"},
		{Name: ".NET", Category: "backend"},
		{Name: "AdonisJS", Category: "backend"},
		{Name: "Sails.js", Category: "backend"},
		{Name: "FeathersJS", Category: "backend"},
		{Name: "LoopBack", Category: "backend"},
		{Name: "Moleculer", Category: "backend"},
		{Name: "tRPC", Category: "backend"},
		{Name: "Hasura", Category: "backend"},
		{Name: "Appwrite", Category: "backend"},
		{Name: "PocketBase", Category: "backend"},
		{Name: "Sanctum", Category: "backend"},
		{Name: "Torch", Category: "backend"},
		{Name: "JAX", Category: "backend"},
		{Name: "TensorFlow", Category: "backend"},
		{Name: "PyTorch", Category: "backend"},
		{Name: "OpenCV", Category: "backend"},

		// CMS & website builders
		{Name: "WordPress", Category: "cms"},
		{Name: "Strapi", Category: "cms"},
		{Name: "Sanity", Category: "cms"},
		{Name: "Contentful", Category: "cms"},
		{Name: "Ghost", Category: "cms"},
		{Name: "Drupal", Category: "cms"},
		{Name: "Joomla", Category: "cms"},
		{Name: "Directus", Category: "cms"},
		{Name: "Payload CMS", Category: "cms"},
		{Name: "Keystone.js", Category: "cms"},
		{Name: "Prismic", Category: "cms"},
		{Name: "Tina CMS", Category: "cms"},
		{Name: "Hygraph", Category: "cms"},
		{Name: "Webflow", Category: "cms"},
		{Name: "Wix", Category: "cms"},
		{Name: "Squarespace", Category: "cms"},
		{Name: "Umbraco", Category: "cms"},
		{Name: "Sitecore", Category: "cms"},
		{Name: "Contentstack", Category: "cms"},
		{Name: "Storyblok", Category: "cms"},
		{Name: "ButterCMS", Category: "cms"},
		{Name: "DotCMS", Category: "cms"},
		{Name: "Magnolia", Category: "cms"},

		// e-commerce
		{Name: "Shopify", Category: "ecommerce"},
		{Name: "WooCommerce", Category: "ecommerce"},
		{Name: "Magento", Category: "ecommerce"},
		{Name: "Saleor", Category: "ecommerce"},
		{Name: "Medusa", Category: "ecommerce"},
		{Name: "BigCommerce", Category: "ecommerce"},
		{Name: "Snipcart", Category: "ecommerce"},
		{Name: "Commerce.js", Category: "ecommerce"},
		{Name: "Solidus", Category: "ecommerce"},
		{Name: "Spree", Category: "ecommerce"},
		{Name: "Lemon Squeezy", Category: "ecommerce"},
		{Name: "Paddle", Category: "ecommerce"},
		{Name: "Stripe", Category: "ecommerce"},

		// devops & infrastructure
		{Name: "Docker", Category: "devops"},
		{Name: "Podman", Category: "devops"},
		{Name: "Kubernetes", Category: "devops"},
		{Name: "Nomad", Category: "devops"},
		{Name: "Terraform", Category: "devops"},
		{Name: "Pulumi", Category: "devops"},
		{Name: "Ansible", Category: "devops"},
		{Name: "Puppet", Category: "devops"},
		{Name: "Chef", Category: "devops"},
		{Name: "SaltStack", Category: "devops"},
		{Name: "GitHub Actions", Category: "devops"},
		{Name: "GitLab CI", Category: "devops"},
		{Name: "Jenkins", Category: "devops"},
		{Name: "CircleCI", Category: "devops"},
		{Name: "Travis CI", Category: "devops"},
		{Name: "ArgoCD", Category: "devops"},
		{Name: "Flux", Category: "devops"},
		{Name: "Helm", Category: "devops"},
		{Name: "Kustomize", Category: "devops"},
		{Name: "AWS", Category: "devops"},
		{Name: "Google Cloud Platform", Category: "devops"},
		{Name: "Azure", Category: "devops"},
		{Name: "DigitalOcean", Category: "devops"},
		{Name: "Linode", Category: "devops"},
		{Name: "Vercel", Category: "devops"},
		{Name: "Netlify", Category: "devops"},
		{Name: "Cloudflare", Category: "devops"},
		{Name: "Nginx", Category: "devops"},
		{Name: "Apache", Category: "devops"},
		{Name: "Caddy", Category: "devops"},
		{Name: "Traefik", Category: "devops"},
		{Name: "HAProxy", Category: "devops"},
		{Name: "Linux", Category: "devops"},
		{Name: "Ubuntu", Category: "devops"},
		{Name: "Debian", Category: "devops"},
		{Name: "Alpine", Category: "devops"},
		{Name: "Prometheus", Category: "devops"},
		{Name: "Grafana", Category: "devops"},
		{Name: "Datadog", Category: "devops"},
		{Name: "Sentry", Category: "devops"},
		{Name: "OpenTelemetry", Category: "devops"},
		{Name: "Istio", Category: "devops"},
		{Name: "Linkerd", Category: "devops"},
		{Name: "Consul", Category: "devops"},
		{Name: "Vault", Category: "devops"},
		{Name: "Vagrant", Category: "devops"},
		{Name: "Packer", Category: "devops"},
		{Name: "OpenFaaS", Category: "devops"},
		{Name: "Knative", Category: "devops"},
		{Name: "Cloud Foundry", Category: "devops"},
		{Name: "Heroku", Category: "devops"},
		{Name: "Railway", Category: "devops"},
		{Name: "Render", Category: "devops"},
		{Name: "Fly.io", Category: "devops"},
		{Name: "Coolify", Category: "devops"},
		{Name: "Koyeb", Category: "devops"},
		{Name: "Northflank", Category: "devops"},
		{Name: "Minikube", Category: "devops"},
		{Name: "Kind", Category: "devops"},
		{Name: "K3s", Category: "devops"},
		{Name: "Rancher", Category: "devops"},
		{Name: "OpenShift", Category: "devops"},
		{Name: "SUSE", Category: "devops"},
		{Name: "CentOS", Category: "devops"},
		{Name: "Fedora", Category: "devops"},
		{Name: "Arch Linux", Category: "devops"},
		{Name: "NixOS", Category: "devops"},
		{Name: "Nix", Category: "devops"},
		{Name: "SSH", Category: "devops"},
		{Name: "OpenSSL", Category: "devops"},
		{Name: "Let's Encrypt", Category: "devops"},
		{Name: "Certbot", Category: "devops"},
		{Name: "Cloudflare Workers", Category: "devops"},
		{Name: "Lambda", Category: "devops"},
		{Name: "S3", Category: "devops"},
		{Name: "CloudFront", Category: "devops"},
		{Name: "ECS", Category: "devops"},
		{Name: "EKS", Category: "devops"},
		{Name: "Fargate", Category: "devops"},
		{Name: "SQS", Category: "devops"},
		{Name: "SNS", Category: "devops"},
		{Name: "CloudWatch", Category: "devops"},
		{Name: "Firebase", Category: "devops"},
		{Name: "Loki", Category: "devops"},
		{Name: "Tempo", Category: "devops"},
		{Name: "Mimir", Category: "devops"},
		{Name: "Jaeger", Category: "devops"},
		{Name: "New Relic", Category: "devops"},

		// databases
		{Name: "PostgreSQL", Category: "database"},
		{Name: "MySQL", Category: "database"},
		{Name: "MariaDB", Category: "database"},
		{Name: "SQLite", Category: "database"},
		{Name: "MongoDB", Category: "database"},
		{Name: "Redis", Category: "database"},
		{Name: "Elasticsearch", Category: "database"},
		{Name: "Cassandra", Category: "database"},
		{Name: "DynamoDB", Category: "database"},
		{Name: "Firestore", Category: "database"},
		{Name: "CockroachDB", Category: "database"},
		{Name: "TiDB", Category: "database"},
		{Name: "ClickHouse", Category: "database"},
		{Name: "InfluxDB", Category: "database"},
		{Name: "TimescaleDB", Category: "database"},
		{Name: "Neo4j", Category: "database"},
		{Name: "ArangoDB", Category: "database"},
		{Name: "Supabase", Category: "database"},
		{Name: "PlanetScale", Category: "database"},
		{Name: "CouchDB", Category: "database"},
		{Name: "RavenDB", Category: "database"},
		{Name: "SurrealDB", Category: "database"},
		{Name: "EdgeDB", Category: "database"},
		{Name: "Fauna", Category: "database"},
		{Name: "RethinkDB", Category: "database"},
		{Name: "HBase", Category: "database"},
		{Name: "Memcached", Category: "database"},
		{Name: "Apache Kafka", Category: "database"},
		{Name: "RabbitMQ", Category: "database"},
		{Name: "NATS", Category: "database"},
		{Name: "Neon", Category: "database"},
		{Name: "DuckDB", Category: "database"},
		{Name: "SQLC", Category: "database"},
		{Name: "BunSqlite", Category: "database"},
		{Name: "Better Sqlite3", Category: "database"},

		// ORMs & database tools
		{Name: "Prisma", Category: "database"},
		{Name: "Drizzle", Category: "database"},
		{Name: "TypeORM", Category: "database"},
		{Name: "Sequelize", Category: "database"},
		{Name: "Knex", Category: "database"},
		{Name: "Mongoose", Category: "database"},
		{Name: "GORM", Category: "database"},
		{Name: "SQLAlchemy", Category: "database"},
		{Name: "Liquibase", Category: "database"},
		{Name: "Flyway", Category: "database"},
		{Name: "Diesel", Category: "database"},
		{Name: "SeaORM", Category: "database"},
		{Name: "SQLx", Category: "database"},
		{Name: "Entity Framework", Category: "database"},
		{Name: "NHibernate", Category: "database"},
		{Name: "Dapper", Category: "database"},
		{Name: "MikroORM", Category: "database"},
		{Name: "Objective Sqlite", Category: "database"},
		{Name: "Redis OM", Category: "database"},

		// mobile
		{Name: "React Native", Category: "mobile"},
		{Name: "Flutter", Category: "mobile"},
		{Name: "SwiftUI", Category: "mobile"},
		{Name: "Jetpack Compose", Category: "mobile"},
		{Name: "Ionic", Category: "mobile"},
		{Name: "Capacitor", Category: "mobile"},
		{Name: "Xamarin", Category: "mobile"},
		{Name: ".NET MAUI", Category: "mobile"},
		{Name: "Expo", Category: "mobile"},
		{Name: "Unity", Category: "mobile"},
		{Name: "Kotlin Multiplatform", Category: "mobile"},
		{Name: "Compose Multiplatform", Category: "mobile"},
		{Name: "NativeScript", Category: "mobile"},
		{Name: "Cordova", Category: "mobile"},
		{Name: "PhoneGap", Category: "mobile"},
		{Name: "Tauri", Category: "mobile"},
		{Name: "Electron", Category: "mobile"},

		// tools & editors
		{Name: "Git", Category: "tool"},
		{Name: "VS Code", Category: "tool"},
		{Name: "IntelliJ IDEA", Category: "tool"},
		{Name: "WebStorm", Category: "tool"},
		{Name: "Vim", Category: "tool"},
		{Name: "Neovim", Category: "tool"},
		{Name: "Emacs", Category: "tool"},
		{Name: "Sublime Text", Category: "tool"},
		{Name: "Zed", Category: "tool"},
		{Name: "Vite", Category: "tool"},
		{Name: "Webpack", Category: "tool"},
		{Name: "Rollup", Category: "tool"},
		{Name: "Parcel", Category: "tool"},
		{Name: "esbuild", Category: "tool"},
		{Name: "Babel", Category: "tool"},
		{Name: "ESLint", Category: "tool"},
		{Name: "Prettier", Category: "tool"},
		{Name: "Husky", Category: "tool"},
		{Name: "pnpm", Category: "tool"},
		{Name: "Yarn", Category: "tool"},
		{Name: "npm", Category: "tool"},
		{Name: "Postman", Category: "tool"},
		{Name: "Insomnia", Category: "tool"},
		{Name: "Swagger", Category: "tool"},
		{Name: "Figma", Category: "tool"},
		{Name: "Storybook", Category: "tool"},
		{Name: "Cypress", Category: "tool"},
		{Name: "Playwright", Category: "tool"},
		{Name: "Vitest", Category: "tool"},
		{Name: "Jest", Category: "tool"},
		{Name: "Mocha", Category: "tool"},
		{Name: "Selenium", Category: "tool"},
		{Name: "Puppeteer", Category: "tool"},
		{Name: "Homebrew", Category: "tool"},
		{Name: "curl", Category: "tool"},
		{Name: "jq", Category: "tool"},
		{Name: "Turbopack", Category: "tool"},
		{Name: "Rspack", Category: "tool"},
		{Name: "Moonrepo", Category: "tool"},
		{Name: "Nx", Category: "tool"},
		{Name: "Turbo", Category: "tool"},
		{Name: "Lerna", Category: "tool"},
		{Name: "Rush", Category: "tool"},
		{Name: "Bazel", Category: "tool"},
		{Name: "NX", Category: "tool"},
		{Name: "React Testing Library", Category: "tool"},
		{Name: "Testing Library", Category: "tool"},
		{Name: "Jasmine", Category: "tool"},
		{Name: "Karma", Category: "tool"},
		{Name: "Ava", Category: "tool"},
		{Name: "Tape", Category: "tool"},
		{Name: "Istanbul", Category: "tool"},
		{Name: "Chai", Category: "tool"},
		{Name: "Sinon", Category: "tool"},
		{Name: "Detox", Category: "tool"},
		{Name: "Appium", Category: "tool"},
		{Name: "Gradle", Category: "tool"},
		{Name: "Maven", Category: "tool"},
		{Name: "Ant", Category: "tool"},
		{Name: "Cargo", Category: "tool"},
		{Name: "Go Modules", Category: "tool"},
		{Name: "Make", Category: "tool"},
		{Name: "CMake", Category: "tool"},
		{Name: "Meson", Category: "tool"},
		{Name: "Sketch", Category: "tool"},
		{Name: "Adobe XD", Category: "tool"},
		{Name: "Penpot", Category: "tool"},
		{Name: "Notion", Category: "tool"},
		{Name: "Linear", Category: "tool"},
		{Name: "Jira", Category: "tool"},
		{Name: "Trello", Category: "tool"},
		{Name: "Asana", Category: "tool"},
		{Name: "Slack", Category: "tool"},
		{Name: "Discord", Category: "tool"},
		{Name: "ngrok", Category: "tool"},
		{Name: "HTTPie", Category: "tool"},
		{Name: "Bruno", Category: "tool"},
		{Name: "Hoppscotch", Category: "tool"},
		{Name: "Wireshark", Category: "tool"},
		{Name: "GDB", Category: "tool"},
		{Name: "LLDB", Category: "tool"},
		{Name: "Valgrind", Category: "tool"},
		{Name: "Perf", Category: "tool"},
		{Name: "Strace", Category: "tool"},
		{Name: "Lsof", Category: "tool"},
		{Name: "Tmux", Category: "tool"},
		{Name: "Screen", Category: "tool"},
		{Name: "Fish", Category: "tool"},
		{Name: "Zsh", Category: "tool"},
		{Name: "Bash", Category: "tool"},
		{Name: "FZF", Category: "tool"},
		{Name: "Ripgrep", Category: "tool"},
		{Name: "FD", Category: "tool"},
		{Name: "Bat", Category: "tool"},
		{Name: "Eza", Category: "tool"},
		{Name: "Lazygit", Category: "tool"},
		{Name: "LazyVim", Category: "tool"},
		{Name: "AstroNvim", Category: "tool"},
		{Name: "Obsidian", Category: "tool"},
		{Name: "Logseq", Category: "tool"},
		{Name: "Tldr", Category: "tool"},
		{Name: "Cheat", Category: "tool"},
	}

	for _, t := range techs {
		slug := normalizeSlug(t.Name)

		_, err := db.Exec(`
			INSERT INTO technologies (name, slug, category, isVerified)
			SELECT ?, ?, ?, true
			WHERE NOT EXISTS (
				SELECT 1 FROM technologies WHERE slug = ?
			)
		`, t.Name, slug, t.Category, slug)

		if err != nil {
			return fmt.Errorf("failed seeding %s: %w", t.Name, err)
		}
	}

	return nil
}
